server:
  port: 8090
spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "configserver:http://localhost:8071/" #newer way to address
  cloud:
    config:
      label: bank_ms # folder under which config files are

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bankmas.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345