build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related PRODUCTION APIs"
  contactDetails:
    name: "Ravi Kiran - Support Manager"
    email: "ravi@eazybank.com"
  onCallSupport:
    - (999) 888-1111
    - (999) 888-2222
