spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: "configserver:http://localhost:8071/" #newer way to address
  cloud:
    config: # optional if default label already mentioned in cs
#      label: bank_ms # folder under which config files are
      label: master # mention git branch
server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bankmas.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
management:
  endpoints:
    web:
      exposure:
        include: "refresh, bus-refresh" # to fetch latest config changes from configserver
